//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IHM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _66203700logo2bis_jpg1 {
            get {
                object obj = ResourceManager.GetObject("_66203700logo2bis_jpg1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;effectuer cette action : elle a déjà été réalisée..
        /// </summary>
        internal static string ActionAlreadyDoneError {
            get {
                return ResourceManager.GetString("ActionAlreadyDoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;effectuer cette action : une erreur est survenue..
        /// </summary>
        internal static string ActionError {
            get {
                return ResourceManager.GetString("ActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Add2 {
            get {
                object obj = ResourceManager.GetObject("Add2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter une nouvelle équipe : une erreur est survenue..
        /// </summary>
        internal static string AddNewTeamError {
            get {
                return ResourceManager.GetString("AddNewTeamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter une nouvelle équipe à ce moment du concours..
        /// </summary>
        internal static string AddTeamInvalidWokflowStateMessage {
            get {
                return ResourceManager.GetString("AddTeamInvalidWokflowStateMessage", resourceCulture);
            }
        }
             
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back {
            get {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Check {
            get {
                object obj = ResourceManager.GetObject("Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteRed {
            get {
                object obj = ResourceManager.GetObject("DeleteRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
                
        /// <summary>
        ///   Looks up a localized string similar to Impossible de définir une nouvelle configuration : une erreur est survenue..
        /// </summary>
        internal static string EditConfigError {
            get {
                return ResourceManager.GetString("EditConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de définir une nouvelle configuration à ce moment du concours..
        /// </summary>
        internal static string EditConfigInvalidWokflowStateMessage {
            get {
                return ResourceManager.GetString("EditConfigInvalidWokflowStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Equipe {
            get {
                object obj = ResourceManager.GetObject("Equipe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
                
        /// <summary>
        ///   Looks up a localized string similar to Une erreur fatale est survenue, le programme va interrompre son éxécution..
        /// </summary>
        internal static string FatalErrorMessage {
            get {
                return ResourceManager.GetString("FatalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Home {
            get {
                object obj = ResourceManager.GetObject("Home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
                
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;effectuer cette action à ce moment du concours..
        /// </summary>
        internal static string InvalidWorkflowStateError {
            get {
                return ResourceManager.GetString("InvalidWorkflowStateError", resourceCulture);
            }
        }
                
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;accèder à l&apos;historique des anciens concours : une erreur est survenue..
        /// </summary>
        internal static string LoadPreviousCompetitionError {
            get {
                return ResourceManager.GetString("LoadPreviousCompetitionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter l&apos;équipe {0} : nombre maximal d&apos;équipes atteind..
        /// </summary>
        internal static string MaxTeamsNumberReached {
            get {
                return ResourceManager.GetString("MaxTeamsNumberReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de démarrer une nouvelle manche aléatoire à ce moment du concours..
        /// </summary>
        internal static string NewRandomRoundInvalidWokflowStateMessage {
            get {
                return ResourceManager.GetString("NewRandomRoundInvalidWokflowStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de démarrer une nouvelle manche aléatoire : nombre maximum atteind..
        /// </summary>
        internal static string NewRandomRoundNumberMessage {
            get {
                return ResourceManager.GetString("NewRandomRoundNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de démarrer une nouvelle manche aléatoire : la manche précédente n&apos;est pas terminée.
        /// </summary>
        internal static string NewRandomRoundPreviousRoundInProgress {
            get {
                return ResourceManager.GetString("NewRandomRoundPreviousRoundInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de démarrer une nouvelle manche aléatoire : le nombre d&apos;équipes est inadapté..
        /// </summary>
        internal static string NewRandomRoundTeamsNumberError {
            get {
                return ResourceManager.GetString("NewRandomRoundTeamsNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de démarrer une nouvelle manche aléatoire : erreur inconnue..
        /// </summary>
        internal static string NewRandomRoundUnknownError {
            get {
                return ResourceManager.GetString("NewRandomRoundUnknownError", resourceCulture);
            }
        }
                
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Next {
            get {
                object obj = ResourceManager.GetObject("Next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Printer_print_3d_vector_symbol_simple_pictogram {
            get {
                object obj = ResourceManager.GetObject("Printer_print_3d_vector_symbol_simple_pictogram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Quit {
            get {
                object obj = ResourceManager.GetObject("Quit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ranking {
            get {
                object obj = ResourceManager.GetObject("Ranking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer  &quot;{0}&quot; : une erreur est survenue..
        /// </summary>
        internal static string RemoveTeamError {
            get {
                return ResourceManager.GetString("RemoveTeamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer une équipe à ce moment du concours..
        /// </summary>
        internal static string RemoveTeamInvalidWokflowStateMessage {
            get {
                return ResourceManager.GetString("RemoveTeamInvalidWokflowStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sans_titre {
            get {
                object obj = ResourceManager.GetObject("Sans_titre", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
                
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sanstitre {
            get {
                object obj = ResourceManager.GetObject("Sanstitre", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Start {
            get {
                object obj = ResourceManager.GetObject("Start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de recharger le concours : une erreur est survenue..
        /// </summary>
        internal static string StartInProgressCompetitionError {
            get {
                return ResourceManager.GetString("StartInProgressCompetitionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is starting.
        /// </summary>
        internal static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de démarrer un nouveau concours : une erreur est survenue..
        /// </summary>
        internal static string StartNewCompetitionError {
            get {
                return ResourceManager.GetString("StartNewCompetitionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter &quot;{0}&quot;, cette équipe est déjà enregistrée..
        /// </summary>
        internal static string TeamAlreadyExistMessage {
            get {
                return ResourceManager.GetString("TeamAlreadyExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer &quot;{0}&quot; : cette équipe n&apos;éxiste pas..
        /// </summary>
        internal static string TeamNotExistMessage {
            get {
                return ResourceManager.GetString("TeamNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue ! Le programme va continuer de s&apos;éxecuter mais il risque d&apos;être instable. Veuillez contacter l&apos;administrateur.	.
        /// </summary>
        internal static string UnhandledErrorMessage {
            get {
                return ResourceManager.GetString("UnhandledErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier l&apos;équipe : une erreur est survenue..
        /// </summary>
        internal static string UpdateTeamError {
            get {
                return ResourceManager.GetString("UpdateTeamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier une équipe à ce moment du concours..
        /// </summary>
        internal static string UpdateTeamInvalidWokflowStateMessage {
            get {
                return ResourceManager.GetString("UpdateTeamInvalidWokflowStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
