namespace IHM.Views.UserControl
{
    partial class HiddenGamesGrid
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.Data.SortDescriptor sortDescriptor1 = new Telerik.WinControls.Data.SortDescriptor();
            this.gameBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.GamesGrid = new Telerik.WinControls.UI.RadGridView();
            ((System.ComponentModel.ISupportInitialize)(this.gameBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.GamesGrid)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.GamesGrid.MasterTemplate)).BeginInit();
            this.SuspendLayout();
            // 
            // gameBindingSource
            // 
            this.gameBindingSource.DataSource = typeof(BLL.Game);
            // 
            // GamesGrid
            // 
            this.GamesGrid.BackColor = System.Drawing.SystemColors.Control;
            this.GamesGrid.Cursor = System.Windows.Forms.Cursors.Default;
            this.GamesGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.GamesGrid.Font = new System.Drawing.Font("Segoe UI", 8.25F);
            this.GamesGrid.ForeColor = System.Drawing.SystemColors.ControlText;
            this.GamesGrid.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.GamesGrid.Location = new System.Drawing.Point(0, 0);
            // 
            // GamesGrid
            // 
            this.GamesGrid.MasterTemplate.AllowColumnChooser = false;
            this.GamesGrid.MasterTemplate.AllowColumnReorder = false;
            this.GamesGrid.MasterTemplate.AllowColumnResize = false;
            this.GamesGrid.MasterTemplate.AllowDragToGroup = false;
            this.GamesGrid.MasterTemplate.AllowRowResize = false;
            this.GamesGrid.MasterTemplate.AutoGenerateColumns = false;
            gridViewDecimalColumn1.DataType = typeof(int);
            gridViewDecimalColumn1.EnableExpressionEditor = false;
            gridViewDecimalColumn1.FieldName = "Board";
            gridViewDecimalColumn1.HeaderText = "Terrain";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.Name = "Board";
            gridViewDecimalColumn1.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            gridViewDecimalColumn1.Width = 43;
            gridViewTextBoxColumn1.EnableExpressionEditor = false;
            gridViewTextBoxColumn1.FieldName = "Team1";
            gridViewTextBoxColumn1.HeaderText = "Equipe 1";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.Name = "Teams";
            gridViewTextBoxColumn1.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            gridViewTextBoxColumn1.Width = 52;
            gridViewTextBoxColumn2.EnableExpressionEditor = false;
            gridViewTextBoxColumn2.FieldName = "Team2";
            gridViewTextBoxColumn2.HeaderText = "Equipe 2";
            gridViewTextBoxColumn2.Name = "column1";
            gridViewTextBoxColumn2.SortOrder = Telerik.WinControls.UI.RadSortOrder.Ascending;
            gridViewTextBoxColumn2.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            gridViewTextBoxColumn2.Width = 52;
            this.GamesGrid.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn1,
            gridViewTextBoxColumn1,
            gridViewTextBoxColumn2});
            this.GamesGrid.MasterTemplate.DataSource = this.gameBindingSource;
            this.GamesGrid.MasterTemplate.EnableGrouping = false;
            this.GamesGrid.MasterTemplate.EnableSorting = false;
            this.GamesGrid.MasterTemplate.ShowRowHeaderColumn = false;
            sortDescriptor1.PropertyName = "column1";
            this.GamesGrid.MasterTemplate.SortDescriptors.AddRange(new Telerik.WinControls.Data.SortDescriptor[] {
            sortDescriptor1});
            this.GamesGrid.Name = "GamesGrid";
            this.GamesGrid.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.GamesGrid.Size = new System.Drawing.Size(565, 497);
            this.GamesGrid.TabIndex = 0;
            this.GamesGrid.Text = "radGridView1";
            // 
            // HiddenGamesGrid
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.GamesGrid);
            this.Name = "HiddenGamesGrid";
            this.Size = new System.Drawing.Size(565, 497);
            ((System.ComponentModel.ISupportInitialize)(this.gameBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.GamesGrid.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.GamesGrid)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.BindingSource gameBindingSource;
        private Telerik.WinControls.UI.RadGridView GamesGrid;
    }
}
