//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;effectuer cette action : elle a déjà été réalisée..
        /// </summary>
        internal static string ActionAlreadyDoneError {
            get {
                return ResourceManager.GetString("ActionAlreadyDoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;effectuer cette action : une erreur est survenue..
        /// </summary>
        internal static string ActionError {
            get {
                return ResourceManager.GetString("ActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter une nouvelle équipe : une erreur est survenue..
        /// </summary>
        internal static string AddNewTeamError {
            get {
                return ResourceManager.GetString("AddNewTeamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter une nouvelle équipe à ce moment du concours..
        /// </summary>
        internal static string AddTeamInvalidWokflowStateMessage {
            get {
                return ResourceManager.GetString("AddTeamInvalidWokflowStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de définir une nouvelle configuration : une erreur est survenue..
        /// </summary>
        internal static string EditConfigError {
            get {
                return ResourceManager.GetString("EditConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de définir une nouvelle configuration à ce moment du concours..
        /// </summary>
        internal static string EditConfigInvalidWokflowStateMessage {
            get {
                return ResourceManager.GetString("EditConfigInvalidWokflowStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur fatale est survenue, le programme va interrompre son éxécution..
        /// </summary>
        internal static string FatalErrorMessage {
            get {
                return ResourceManager.GetString("FatalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string InformationMessage {
            get {
                return ResourceManager.GetString("InformationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;effectuer cette action à ce moment du concours..
        /// </summary>
        internal static string InvalidWorkflowStateError {
            get {
                return ResourceManager.GetString("InvalidWorkflowStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;accèder à l&apos;historique des anciens concours : une erreur est survenue..
        /// </summary>
        internal static string LoadPreviousCompetitionError {
            get {
                return ResourceManager.GetString("LoadPreviousCompetitionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter l&apos;équipe {0} : nombre maximal d&apos;équipes atteind..
        /// </summary>
        internal static string MaxTeamsNumberReached {
            get {
                return ResourceManager.GetString("MaxTeamsNumberReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de démarrer une nouvelle manche aléatoire à ce moment du concours..
        /// </summary>
        internal static string NewRandomRoundInvalidWokflowStateMessage {
            get {
                return ResourceManager.GetString("NewRandomRoundInvalidWokflowStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de démarrer une nouvelle manche aléatoire : nombre maximum atteind..
        /// </summary>
        internal static string NewRandomRoundNumberMessage {
            get {
                return ResourceManager.GetString("NewRandomRoundNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de démarrer une nouvelle manche aléatoire : la manche précédente n&apos;est pas terminée.
        /// </summary>
        internal static string NewRandomRoundPreviousRoundInProgress {
            get {
                return ResourceManager.GetString("NewRandomRoundPreviousRoundInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de démarrer une nouvelle manche aléatoire : le nombre d&apos;équipes est inadapté..
        /// </summary>
        internal static string NewRandomRoundTeamsNumberError {
            get {
                return ResourceManager.GetString("NewRandomRoundTeamsNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de démarrer une nouvelle manche aléatoire : erreur inconnue..
        /// </summary>
        internal static string NewRandomRoundUnknownError {
            get {
                return ResourceManager.GetString("NewRandomRoundUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de démarrer une nouvelle manche de classement à ce moment du concours..
        /// </summary>
        internal static string NewRankingRoundInvalidWokflowStateMessage {
            get {
                return ResourceManager.GetString("NewRankingRoundInvalidWokflowStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de démarrer une nouvelle manche de classement : nombre maximum atteind..
        /// </summary>
        internal static string NewRankingRoundNumberMessage {
            get {
                return ResourceManager.GetString("NewRankingRoundNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de démarrer une nouvelle manche de classement : la manche précédente n&apos;est pas terminée.
        /// </summary>
        internal static string NewRankingRoundPreviousRoundInProgress {
            get {
                return ResourceManager.GetString("NewRankingRoundPreviousRoundInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de démarrer une nouvelle manche de classement : le nombre d&apos;équipes est inadapté..
        /// </summary>
        internal static string NewRankingRoundTeamsNumberError {
            get {
                return ResourceManager.GetString("NewRankingRoundTeamsNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de démarrer une nouvelle manche de classement : erreur inconnue..
        /// </summary>
        internal static string NewRankingRoundUnknownError {
            get {
                return ResourceManager.GetString("NewRankingRoundUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer  &quot;{0}&quot; : une erreur est survenue..
        /// </summary>
        internal static string RemoveTeamError {
            get {
                return ResourceManager.GetString("RemoveTeamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer une équipe à ce moment du concours..
        /// </summary>
        internal static string RemoveTeamInvalidWokflowStateMessage {
            get {
                return ResourceManager.GetString("RemoveTeamInvalidWokflowStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de recharger le concours : une erreur est survenue..
        /// </summary>
        internal static string StartInProgressCompetitionError {
            get {
                return ResourceManager.GetString("StartInProgressCompetitionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is starting.
        /// </summary>
        internal static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de démarrer un nouveau concours : une erreur est survenue..
        /// </summary>
        internal static string StartNewCompetitionError {
            get {
                return ResourceManager.GetString("StartNewCompetitionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter &quot;{0}&quot;, cette équipe est déjà enregistrée..
        /// </summary>
        internal static string TeamAlreadyExistMessage {
            get {
                return ResourceManager.GetString("TeamAlreadyExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer &quot;{0}&quot; : cette équipe n&apos;éxiste pas..
        /// </summary>
        internal static string TeamNotExistMessage {
            get {
                return ResourceManager.GetString("TeamNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue ! Le programme va continuer de s&apos;éxecuter mais il risque d&apos;être instable. Veuillez contacter l&apos;administrateur.	.
        /// </summary>
        internal static string UnhandledErrorMessage {
            get {
                return ResourceManager.GetString("UnhandledErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier l&apos;équipe : une erreur est survenue..
        /// </summary>
        internal static string UpdateTeamError {
            get {
                return ResourceManager.GetString("UpdateTeamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de modifier une équipe à ce moment du concours..
        /// </summary>
        internal static string UpdateTeamInvalidWokflowStateMessage {
            get {
                return ResourceManager.GetString("UpdateTeamInvalidWokflowStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avertissement.
        /// </summary>
        internal static string WarningMessage {
            get {
                return ResourceManager.GetString("WarningMessage", resourceCulture);
            }
        }
    }
}
